### ISSUE TITLE
Secret Manager are wrongly implemented 

### ISSUE THREAD

**Issue by nmondal** [nmondal/cowj#128]
Other than `local` that is.

Note that a secret manager is practically a  Secret Env Map of String, String really.
However, we do not implement it that way.

Ideally one should be able to fetch list of secrets.
More importantly, they should NOT be allowed to fetch arbitrary secrets.
In this regard, the secret manager should be enumerated fixed size dictionary.

Something like this works out:

```yaml
plugins:
  cowj.plugins:
    azure_key_vault: SecretManager::AKV

data-sources:

   cloud-secret-mgr:
      type: azure_key_vault
      reload:  60  # in minutes 
      keys:
         jdbc_con : str  
         foo-bar : int 
         what-ever-works : json 


    pgsql:
        type: jdbc
        secrets : cloud-secret-mgr 
        connection :  ${jdbc_con}
    
```

**Comment by HemilTheRebel** [comment]
This makes sense

**Comment by nmondal** [comment]
In the latest pull we have designed ( w/o the reload ) -- and `keys` changed into `config` as follows:

```yaml
cloud-secret-mgr:
      type: azure_key_vault
      config:
         jdbc_con : str  
         foo-bar : int 
         what-ever-works : json 
```
Note that `config` can actually be a `string`, a `list` or a `map` . If it is a string, behaviour is exactly same as earlier.
If it is a list then that depicts the keys, and if it is a map the keys of the map are the secret keys.

The values for the `config` map are for documentation purposes,  to demonstrate what actual values it stores.
