### ISSUE TITLE
If we want to just use Cowj for static webserver - it does not work 

### ISSUE THREAD

**Issue by nmondal** [nmondal/cowj#130]
W/o route mapping or any mapping there was no initialization only, hence it fails.
Also in a static web server context - you still need to specify the "/" mapping. 

Now there are many ways to do it, simplest is - making `static` folder point to a static file.
Or, introduce a new map - either the static is a folder or a map.

If static is not a string/folder, then static is treated as a map.

something like this:

```yaml

static: 
   dir :  foo-bar 
   root: foo-bar/pages/index.html

```
