### ISSUE TITLE
Given same path prefix with routes and proxies, routes take precedence - but with no warning

### ISSUE THREAD

**Issue by nmondal** [nmondal/cowj#134]
Observe this:

```yaml
# users/users.yaml
port: 9090
routes:
  get:
    /api/v1/users/:id: _/api/v1/users.zm
    /api/v1/users: _/api/v1/users.zm

  post:
    /api/v1/users: _/api/v1/postuser.zom

# route forwarding local /users points to json_place
proxies:
  get:
    /api/v1/users: json_place/users
  post:
    /users: json_place/users

# how to load various data sources - plugin based architecture 
plugins:
  # the package 
  cowj.plugins:
    # items from each package class::field_name
    curl: CurlWrapper::CURL
    redis: RedisWrapper::REDIS

# data store connections
data-sources:
  redis :
    type : redis
    urls: [ "localhost:6379"]

  json_place:
    type: curl
    url: https://jsonplaceholder.typicode.com
```

In this file, the path `/api/v1/users/:id: ` is routed.
While thepath `/api/v1/users `  is proxied.

The proxy does not work, and no warning / error are given when boot/run.
