### ISSUE TITLE
For development it would be better to have options to "auto-load" 

### ISSUE THREAD

**Issue by nmondal** [nmondal/cowj#38]
We can start with Scripts, all scripts. Functionality would be encoded in the Yaml file as follows:

```yaml
cache : 
     scripts: false
     auth: false 
     type: false 
```
Default would be set to true.
This way people do not have to reload the server - when they modify things in the scripts and such.
We should start with `scripts` and `type`.

A much better alternative would be just adding `cache : false` in the container `yaml` files.

Main config file cache would essentially talk about scripts in question.
`Schema.yaml` would only be applicable for  JSON files pointed to by the schema.
