### ISSUE TITLE
RedisWrapper does not use SecretManager properly

### ISSUE THREAD

**Issue by nmondal** [nmondal/cowj#40]
This would  be a problem:

```yaml
local_redis:
   type: redis
   secrets : gcp
   urls: "${redis-urls}"
```
Would not work even if the `gcp` secret manager has a proper key which is `redis-urls`
