### ISSUE TITLE
Cloud storage plugin does not provide an option to override project id

### ISSUE THREAD

**Issue by hemil-ruparel-blox** [nmondal/cowj#49]
# Issue Description

The cloud storage plugin uses the gcloud default project id. This will not work if project id is not set or if you have multiple projects and want to work with them at the same time. A lot of people have access to the project but might not have set a default project id. And a lot of people might have multiple projects and might not want to change defaults everytime they change projects. Forgetting to change default project might end up with them getting weird error messages.

## Proposed solution
In the yaml file, add an optional field for project-id.

If project-id is not specified, use gcloud default
```yaml
plugins:
  cowj.plugins:
    g_storage: GoogleStorageWrapper::STORAGE

data-sources:
  storage:
    type: g_storage
```

With project-id specified
```yaml
plugins:
  cowj.plugins:
    g_storage: GoogleStorageWrapper::STORAGE

data-sources:
  storage:
    type: g_storage
    project-id: foo_bar
```
