### ISSUE TITLE
Preflight request Authentication - OPTIONS 

### ISSUE THREAD

**Issue by nmondal** [nmondal/cowj#51]
As one can see from here:
https://serverfault.com/questions/684855/disable-authentication-for-http-options-method-preflight-request
For CORS, the preflight would be a problem - it needs to be Authenticated, which will not work.
Apache2 solves the problem by putting 

```xml
<LimitExcept OPTIONS>
  Require valid-user
</LimitExcept>
```

**Comment by nmondal** [comment]
More insight came up - it seems the fix is avoid Auth in OPTIONS.
https://stackoverflow.com/questions/40722700/add-authentication-to-options-request

**Comment by hemil-ruparel-blox** [comment]
Yep. This will happen for every API that is to be consumed on web. Therefore, I propose the following solution.

In the yaml file, add a cors section like so:

```yaml
cors:
  origin: https://foo.example # sets Access-Control-Allow-Origin
  methods: POST, GET, OPTIONS # sets Access-Control-Allow-Methods
  headers: X-PINGOTHER, Content-Type # Access-Control-Allow-Headers
  age: 86400 #sets Access-Control-Max-Age
```

In `cors` at least one of the above 4 should be set. If a field is not set, that header will not be set. If `cors` exist in yaml file, it will be as if some one added a route:
```yaml
options: 
  "*": _/cors.zm
```

Where cors.zm sets the appropriate headers.
