### ISSUE TITLE
Output filter for proxy does not validate response after finally filter

### ISSUE THREAD

**Issue by hemil-ruparel-blox** [nmondal/cowj#65]
Say I have an API Get Request to '/' which forwards the request to some other API and then messages the data and returns it. In this case I want the output validation to trigger after the finally filter because I want to handle both error and success case. Right now what is happening is it is triggering before finally.

Example - 
api.yaml
```yaml
port: 5003

proxies:
  get:
    /: json_place/users

filters:
  finally:
    /: _/after.zm

plugins:
  cowj.plugins:
    curl: CurlWrapper::CURL

data-sources:
  json_place:
    type: curl
    url: https://jsonplaceholder.typicode.com
```

static/types/schema.yaml
```yaml
labels: # how system knows which label to invoke
  ok:  "resp.status == 200" # when response status is 200
  err:  "resp.status != 200" # when it is not

verify:
  out: true

routes:
  /:
    get:
      ok: output.json
```

static/types/output.json
```json
{
  "$id": "https://blox.xyz/cowj_api/Generic.error.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Output for send otp service",
  "title": "Error",
  "type": "object",
  "properties": {
    "foo": {
      "type": "string"
    }
  },
  "required": ["foo"],
  "additionalProperties": false
}
```

after.zm
```groovy
resp.body("{\"foo\": \"bar\"}")
```

This setup responds with: `{"foo": "bar"}` correctly but on the console, there is a log:
```
SEVERE: Output Schema Validation failed. Route '/' : 
 com.worldturner.medeia.api.ValidationFailedException: [Validation Failure
------------------
Rule:     type
Message:  Type mismatch, data has array and schema has object....
```

As the schema validation expects `{"foo": "bar"}` but it is getting the response from proxy directly before the finally filter.

If we change it to after, it works. 

Expectation - 
For Proxy, Output validation should trigger after all finally filters are executed because we might want to message the data before returning response using after and finally filters. Finally is important because it allows us to handle error case as well
