### ISSUE TITLE
If script returns null, COWJ returns 404

### ISSUE THREAD

**Issue by hemil-ruparel-blox** [nmondal/cowj#92]
92.yaml:
```yaml
port: 5003

routes:
  get:
    /a: _/a.zm
```

```groovy
null
```

Curl:
```sh
curl localhost:5003/a
```

Actual Output:
```
<html><body><h2>404 Not found</h2></body></html>
```

Expected: Empty response maybe?
