### ISSUE TITLE
RAMA  should have it's own `cron` system to run consumers

### ISSUE THREAD

**Issue by nmondal** [nmondal/cowj#94]
Specifically, this is a good way to setup auto-consumers:

```yaml
  rama:
    type: jvm-rama
    storage: storage
    uuid: "rama-42-0"
    topics:
      EVENT_1: 
        at: "0 0/1 * * * ?"
        prefix: "yyyy/MM/dd/HH/mm"
        offset: "PT-1M" 
        step: "PT1M"
        consumers:
          - _/processors/evt_1.zm
      EVENT_2: 
        at: "0 */5 * * * *"
        prefix: "yyyy/MM/dd/HH/mm"
        offset: "PT-5M" 
        step: "PT1M"
        consumers:
          - _/processors/evt_1.zm
          - _/processors/evt_2.zm

```
This looks super clean and start making sense.
